# Generated by Django 2.0.7 on 2018-09-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180921_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(max_length=50)),
                ('computer_model_name', models.CharField(max_length=50)),
                ('computer_color', models.CharField(max_length=20)),
            ],
        ),
    ]
